@startuml DesignClassModel

    class Player {
        -name : String
        -gender : Gender
        -health : int
        -score : int
        -inventory : Item[]
        -currentuDirection : Direction
        +Player()
        +getName()
        +setName()
        +getGender()
        +setGender()
        +decreaseHealth()
        +increaseHealth()
        +getHealth()
        +getInventory()
        +insertItem()
        +removeItem()
    }

    enum Gender {
        MALE
        FEMALE
        NEUTRAL
    }
    enum Direction {
        NORTH
        SOUTH
        EAST
        WEST
    }
    class Enemy
    class GameFrame {
        x : int
        y : int
        GameFrame()
    }
    class Game
    class Main {
        main()
    }
    class Item
    class Map
    class Room

    Player ..|> Gender
    Map ..|> Room
    Player ..|> Item
    Player ..|> Direction

@enduml
