@startuml DomainModel

    object Player{
        name
        gender
        health
        score
        inventory
    }

    object Map
    object Rooms
    object Enemy
    object Items{
        weight
    }

    Player "1" -- "1" Enemy : attacks < 
    Rooms "20" -- "1" Map : are part of >
    Items "0..10" -- "1" Player : collect <
    Enemy "1" -- "1" Map : acts in >
    Player "1" -- "1" Map : plays in >
    Items "0..*" -- "1" Rooms : are in >

@enduml