@startuml DesignClassModel

    Title Design Class Model

    class Player {
        -health : int
        -ArrayIndexCount : int
        -WeightCount : int
        -hidden : boolean
        -inventory : Item[]
        -notesInventory : Note[]
        -notesCount : int
        -currentuDirection : Direction

        +Player()
        +decreaseHealth()
        +increaseHealth()
        +getHealth()
        +getInventory()
        +insertItem()
        +removeItem()
        +getItem()
        +getInventoryCount()
        +getNotesInventory()
        +getNotesCount()
        +getNoteAt()
        +getWeight()
        +printInventory()
        +crossDoor()
        +changeDirection()
        +getCurrentDirection()
        +isHidden()
        +setHidden()
        +equals()
        +clone()
        -compactedInventory()
    }

    class GameMemento{
        -player : Player
        -wall : Wall
        -enemy : Enemy
        -isGameOn : boolean
        -count : int

        GameMemento()
        +getPlayer()
        +getMap()
        +getEnemy()
        +getIsGameOn()
        +getCount()
    }

    class GameCaretaker{
        -mementos : Stack

        +GameCaretaker()
        +addMemento()
        +getMemento()
        +size()
    }

    enum Gender {
        MALE
        FEMALE
        NEUTRAL
    }

    enum Direction {
        NORTH
        SOUTH
        EAST
        WEST
    }

    enum LockType {
        KEY
        COMBINATION
        NONE
    }

    class Enemy{
        +move()
        +Enemy()
        +equals()
        +clone()
        -generateStartingPoint()
    }

    class GameFrame {
        -game : Game
        -wallcount : int
        -images : Image[]
        -isFullscreen : boolean
        - gd : GraphicsDevice
        -frame : JFrame
        -terminal : JTextPane
        inputField : JTextField
        buttonPanel : JPanel
        gameStatusLabel : JLabel
        playerHealthLabel : JLabel
        +GameFrame()
        -updatePlayerHealthLabel()
        -toggleFullscreen()
        -writeToTerminal()
        -clearTerminal()
    }

    class Game {
        -player : Player
        -map : Map
        -enemy : Enemy
        -enemycount: int
        -count : int
        -isGameOn : boolean
        -caretaker : GameCaretaker
        -enemycount : int {final}
        -enemyAttacks : boolean {final}
        
        +Game()
        +nextMove()
        +isGameOver()
        +isGameOn()
        +getPlayer()
        +getMap()
        +getEnemy()
        +undo()
        -saveCurrentState()
        -playerTurn()
        -enemyTurn()
        -capitalizeFirstLetter()
        -getItemsInWall()
    }

    class Main {
        +main()
    }

    class Item{
        #name : String
        #icon : ImageIcon
        #WEIGHT : int {final}
        #PICKABLE : boolean {final}
        #currentRoom : int
        #usingMessage : String

        +Item()
        +getIcon()
        +getRoom()
        +getName()
        +getUsingMessage()
        +setRoom()
        -setName()
        +clone()
        +equals()
    }

    class ClueItem{
        +ClueItem()
        +clone()
        +equals()
    }

    class HiderItem{
        -hiding : boolean
        -hiddenItem : Item

        +HiderItem()
        +isHiding()
        +reveal()
        +clone()
        +equals()
    }

    class ItemContainer{
        -items : Item[]
        -ArrayIndexCount : int
        -locked : boolean
        -lockType : LockType
        -ID : int

        +ItemContainer()
        +removeItem()
        +unlock()
        +setUsingMessage()
        +getItem()
        +getItemsLength()
        +isLocked()
        +getLockType()
        +getID()
        +clone()
        +equals()
    }

    class CustomOutputStream{
        -textPane : JTextPane
        
        +CustomOutputStream()
        +write()
    }

    class HidingItem{
        +HidingItem()
    }

    class HealingItem{
        +HEALING_POINTS : int

        +HealingItem()
        +clone()
        +equals()
    }

    class Note {
        -message : String

        +Notes()
        +clone()
        +equals()
    }

    class Key {
        +ID : int

        +Key()
        +clone()
        +equals()
    }

    class Map {
        -DoorWall : Wall[]
        -PlainWall : Wall[]
        -rooms : Room[]

        +Map()
        +getRoom()
        +clone()
        +getWall()
        +setWall()
    }

    class Room {
        -roomNumber : int
        -doors : int
        -name : String
        -NWall : Wall
        -SWall : Wall
        -EWall : Wall
        -WWall : Wall
        -crossableNorth : boolean
        -crossableSouth : boolean
        -crossableEast : boolean
        -crossableWest : boolean
        -Walls : Wall[]

        +Room()
        +loadImages()
        +getName()
        +getRoomNumber()
        +getDoors()
        +addPassageWay()
        +getNWall()
        +getSWall()
        +getEWall()
        +getWWall()
        +setNwall()
        +setSWall()
        +setEWall()
        +setWWall()
        +getCrossableNorth()
        +getCrossableSouth()
        +getCrossableEast()
        +getCrossableWest()
        +clone()
        +equals()
    }
    
    class Character {
        #name : String
        #gender : Gender
        #currentRoom : int

        +Character()
        +getName()
        +getGender()
        +getCurrentRoom()
        +setCurrentRoom()
        +setName()
        +setGender()
        +getPronoun()
    }

    class Wall
    {
        -wall : BufferedImage
        -hasDoor : boolean
        -itemsImages : HashMap
        -combined : BufferedImage
        -items : Item[]
        -lastItem : int
        
        +Wall()
        +addItemImages()
        +hasDoor()
        +removeItemImage()
        +getCombinedImage()
        +setDoor()
        +getItem()
        +getItemsLength()
        +hasItems()
        +setItems()
        +removeItem()
        +clone()
        +equals()
        -deepCopy()
        -drawItems()
    }

    Player ..|> Gender
    LockType <|.. ItemContainer
    Map ..o "9" Room : has
    Room ..o "4" Wall :has
    Player ..|> "0...*"Item : uses 
    Wall ..|> "0...*" Item : has
    Player ..|> Direction
    Key --|> Item : extends
    HiderItem --|> Item : extends
    ItemContainer --|> Item : extends
    HealingItem --|> Item : extends
    ClueItem --|> Item : extends
    HidingItem --|> Item : extends
    Note --|> Item : extends
    Enemy ..|> Gender
    Character <|-- Player : extends
    Character <|-- Enemy : extends
    Player --o "1" Game
    Map --o "1" Game
    Enemy --o "1" Game
    GameMemento --* Game
    GameCaretaker --* GameMemento
    Game ..|> GameCaretaker : uses
    Game --o GameFrame
    GameFrame <|-- Main
    CustomOutputStream --* GameFrame

@enduml
