@startuml DomainModel

    object Player{
        name
        gender
        health
        inventory
    }

    object Map{
        number of rooms
    }
    object Rooms{
        walls
        number
        name
    }
    object Enemy{
        name
        gender
    }
    object Items{
        name
        weight
        pickable state
    }

    Player "1" -- "1" Enemy : attacks < 
    Rooms "9" -- "1" Map : are part of >
    Items "0..10" -- "1" Player : collect <
    Enemy "1" -- "1" Map : acts in >
    Player "1" -- "1" Map : plays in >
    Items "0..*" -- "1" Rooms : are in >

@enduml