@startuml Player Configuration

title Player Configuration - Internal Sequence DiagramBorderColor

actor User
participant GameFrame
participant Game
participant Player

activate GameFrame
GameFrame --> User: Asks for a name and a gender for the player
User -> GameFrame : provides the asked parameters

activate Game
GameFrame -> Game: Game()

activate Player
Game -> Player: Player()
Player --> Game : Returns the player object

deactivate Player
deactivate Game

@enduml