@startuml SystemSequenceDiagram

actor Player
participant Game

Game --> Player : Shows the start page

alt click on "New Game"
    Player -> Game : New Game
    Game --> Player : Asks for name and gender of the Player    
    Player -> Game : Gives the requested parameters
else click on "Load Game"
    Player -> Game : Load Game
end

Game --> Player : Shows game interface

alt insert an input in the TextField
    Player -> Game : submit a command
    alt command is  "<direction>"
        Game --> Player : Shows the wall n, e, w, s of the current room
    else command is "cross <direction>"
        alt no door in the specified direction in current room
            Game --> Player : returns an error message
        else 
            Game --> Player : moves player in the desired room
        end
    else command is "cross"
        Game --> Player : moves player in the room in the direction he is facing
    else command is "look"
        Game --> Player : Returns a list of the usable items in the wall the player is facing
    else command is "take <item>"
        alt the item is in the room and can fit the inventory
            Game --> Player : Add the item to player's inventory
        else the item can't be taken
            Game --> Player : Return an error message
        end
    else command is "use <item>"
        alt the item is in the inventory or can be used in the room
            Game --> Player : Let the player use the object
        else the object is not in the inventory or can't be used 
            Game --> Player : Return an error message
        end
    else command is "inventory"
        Game --> Player : Shows all the items in player's inventory
    else command is "status"
        Game --> Player : Shows the status of the player (health, room and invenotry)
    end
else submit "undo"/"back" command
    Game --> Player : returns the state of the game one step back
else submit "help" command
    Game --> Player : shows the instruction page with all the commands the player can use
else submit "save" command
    Game --> Player : Save the state of the game
else clicks on "Exit"
    Player -> Game : Exit
        alt the game was saved
            Game --> Player : Exit the game saving changes
        else the game was not saved
            Game --> Player : Asks if the user wants to save the game
            Player -> Game : Says "yes" or "no"
            Game --> Player : Exit the game saving or not saving the progress of the game
        end
end

@enduml