@startuml Undo

title Undo Command - Intenal Sequence Diagram

actor User
participant GameFrame
participant Game
participant GameMemento

activate GameFrame
User -> GameFrame : insert "undo"/"back" as a command

activate Game
GameFrame -> Game : "undo" or "back"

Game -> Game : undo()
GameMemento -> Game : gives the state of the previous move
alt "game has no previous moves" 
    Game -> GameFrame : notify "No previous moves to undo"
else "game has previous moves"
    Game -> Game : update the state of the game with the previous move

    Game -> GameFrame : notify "Undo successful"
deactivate Game
end

GameFrame -> User : display updated game state

deactivate GameFrame

@enduml