@startuml UndoInternalSequenceDiagram

title Undo Command - Intenal Sequence Diagram

actor User
participant GameFrame
participant GameManager
participant Game
participant GameMemento
participant GameCaretaker

activate GameFrame
User -> GameFrame : insert "undo"/"back" as a command

activate GameManager
GameFrame -> GameManager : "undo" or "back"

activate Game
GameManager -> Game : nextMove("undo")

Game -> Game : undo()
activate GameCaretaker
Game -> GameCaretaker : getMemento()
GameCaretaker --> Game : Returns the last mememnto he has saved 
deactivate GameCaretaker

alt "game has no previous moves" 
    Game -> GameManager : notify "No previous moves to undo"
else "game has previous moves"
    activate GameMemento
    Game -> GameMemento : getPlayer()
    GameMemento --> Game : Returns the player
    Game -> GameMemento : getEnemy()
    GameMemento --> Game : Returns the enemy
    Game -> GameMemento : getWall()
    GameMemento --> Game : Returns the wall
    deactivate GameMemento

    Game -> GameManager : notify "Undo successful"
    deactivate Game
end

GameManager -> GameFrame : returns the message to display
deactivate GameManager

GameFrame -> User : display updated game state

deactivate GameFrame

@enduml