@startuml UseCasesDiagram

title Use Cases Diagram

(Start: starts the game) as (start)
(Player Configuration: user select the name and the gender of the player) as (config)
(Command: user intetract with the game) as (command)
(Win: user wins the game completing the final puzzle) as (win)
(Undo: revert the last move) as (undo)
(Save: saves the actual state of the game) as (save)

User -up-> (start)
User -up-> (config)
User -up-> (command)
User -down-> (win)
User -down-> (undo)
User -down-> (save)

@enduml